//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGHv1._0.LimpiezaHabitaciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoLimpieza
    {
        public int idEmpleadoLimpieza { get; set; }
        public string Nombre { get; set; }
        public string Dni { get; set; }
    }
}
