//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGHv1._0.LimpiezaHabitaciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        public int IdHabitacion { get; set; }
        public string Numero { get; set; }
        public Nullable<int> CodTipoHabitacion { get; set; }
        public Nullable<int> CodCategoriaHabitacion { get; set; }
        public Nullable<int> Precio { get; set; }
        public string EstadoHabitacion { get; set; }
    }
}
