//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGHv1._0.LimpiezaHabitaciones
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanillaLimpieza
    {
        public int IdPlanillaLimpieza { get; set; }
        public Nullable<int> IdEmpleadoLimpieza { get; set; }
        public Nullable<int> IdHabitacion { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public Nullable<bool> EstaAsignada { get; set; }
    }
}
